services:
  mongodb:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - todo_app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    
  mongo-ui:
    image: mongo-express:latest
    container_name: mongo-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - todo_app

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - path: .env

    restart: unless-stopped

    networks:
      - todo_app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
    - path: .env

    networks:
      - todo_app
   

networks:
  todo_app:
    driver: bridge

volumes:
  mongo-data: